name: Docker Image CI

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  moose-ubuntu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push on tag
        if: GITHUB_REF_TYPE == "tag"
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:general"
          push: true
          tags: nomoosey/moose-ubuntu:latest,nomoosey/moose-ubuntu:${GITHUB_REF_NAME}
      -
        name: Build and push on branch
        if: GITHUB_REF_TYPE == "branch"
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:general"
          push: true
          tags: nomoosey/moose-ubuntu:${GITHUB_REF_NAME}-$(date +'%Y-%m-%d')-${GITHUB_RUN_NUMBER}
