name: Build sonarr init container

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarr-init:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: checkout
        uses: actions/checkout@v3

      - name: Create mount directories
        run: sudo mkdir -p /init/sonarr_config
      - run: ls -lh /
      - run: ls -lh /init/
      - name: Launch container
#         run: cd sonarr && docker-compose up -d
        run: docker run -d --name sonarr -v /init/sonarr_config:/config linuxserver/sonarr
      - run: ls -lh /init/sonarr_config
      -
        name: Build and push on tag
        if: github.ref_type == 'tag'
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:sonarr"
          push: true
          tags: nomoosey/sonarr-init:latest,nomoosey/sonarr-init:${{github.ref_name}}
      -
        name: Build and push on branch
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:sonarr"
          push: true
          tags: nomoosey/sonarr-init:${{github.ref_name}}-${{github.run_number}}
